// Code generated by mockery v2.53.6. DO NOT EDIT.

package runner

import (
	context "context"

	domain "github.com/nojyerac/aeneas/domain"
	mock "github.com/stretchr/testify/mock"

	runner "github.com/nojyerac/aeneas/runner"
)

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, step
func (_m *MockRunner) Execute(ctx context.Context, step *domain.StepDefinition) *runner.Result {
	ret := _m.Called(ctx, step)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *runner.Result
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StepDefinition) *runner.Result); ok {
		r0 = rf(ctx, step)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runner.Result)
		}
	}

	return r0
}

// MockRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - step *domain.StepDefinition
func (_e *MockRunner_Expecter) Execute(ctx interface{}, step interface{}) *MockRunner_Execute_Call {
	return &MockRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, step)}
}

func (_c *MockRunner_Execute_Call) Run(run func(ctx context.Context, step *domain.StepDefinition)) *MockRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StepDefinition))
	})
	return _c
}

func (_c *MockRunner_Execute_Call) Return(_a0 *runner.Result) *MockRunner_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRunner_Execute_Call) RunAndReturn(run func(context.Context, *domain.StepDefinition) *runner.Result) *MockRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
