// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/nojyerac/aeneas/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockWorkflowRepository is an autogenerated mock type for the WorkflowRepository type
type MockWorkflowRepository struct {
	mock.Mock
}

type MockWorkflowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowRepository) EXPECT() *MockWorkflowRepository_Expecter {
	return &MockWorkflowRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, workflow
func (_m *MockWorkflowRepository) Create(ctx context.Context, workflow *domain.Workflow) error {
	ret := _m.Called(ctx, workflow)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Workflow) error); ok {
		r0 = rf(ctx, workflow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWorkflowRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - workflow *domain.Workflow
func (_e *MockWorkflowRepository_Expecter) Create(ctx interface{}, workflow interface{}) *MockWorkflowRepository_Create_Call {
	return &MockWorkflowRepository_Create_Call{Call: _e.mock.On("Create", ctx, workflow)}
}

func (_c *MockWorkflowRepository_Create_Call) Run(run func(ctx context.Context, workflow *domain.Workflow)) *MockWorkflowRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Workflow))
	})
	return _c
}

func (_c *MockWorkflowRepository_Create_Call) Return(_a0 error) *MockWorkflowRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Workflow) error) *MockWorkflowRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockWorkflowRepository) Get(ctx context.Context, id string) (*domain.Workflow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Workflow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Workflow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkflowRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWorkflowRepository_Expecter) Get(ctx interface{}, id interface{}) *MockWorkflowRepository_Get_Call {
	return &MockWorkflowRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockWorkflowRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockWorkflowRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWorkflowRepository_Get_Call) Return(_a0 *domain.Workflow, _a1 error) *MockWorkflowRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Workflow, error)) *MockWorkflowRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockWorkflowRepository) List(ctx context.Context, opts domain.ListOptions) ([]*domain.Workflow, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListOptions) ([]*domain.Workflow, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListOptions) []*domain.Workflow); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkflowRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts domain.ListOptions
func (_e *MockWorkflowRepository_Expecter) List(ctx interface{}, opts interface{}) *MockWorkflowRepository_List_Call {
	return &MockWorkflowRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockWorkflowRepository_List_Call) Run(run func(ctx context.Context, opts domain.ListOptions)) *MockWorkflowRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListOptions))
	})
	return _c
}

func (_c *MockWorkflowRepository_List_Call) Return(_a0 []*domain.Workflow, _a1 error) *MockWorkflowRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowRepository_List_Call) RunAndReturn(run func(context.Context, domain.ListOptions) ([]*domain.Workflow, error)) *MockWorkflowRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, workflow
func (_m *MockWorkflowRepository) Update(ctx context.Context, workflow *domain.Workflow) error {
	ret := _m.Called(ctx, workflow)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Workflow) error); ok {
		r0 = rf(ctx, workflow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWorkflowRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - workflow *domain.Workflow
func (_e *MockWorkflowRepository_Expecter) Update(ctx interface{}, workflow interface{}) *MockWorkflowRepository_Update_Call {
	return &MockWorkflowRepository_Update_Call{Call: _e.mock.On("Update", ctx, workflow)}
}

func (_c *MockWorkflowRepository_Update_Call) Run(run func(ctx context.Context, workflow *domain.Workflow)) *MockWorkflowRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Workflow))
	})
	return _c
}

func (_c *MockWorkflowRepository_Update_Call) Return(_a0 error) *MockWorkflowRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Workflow) error) *MockWorkflowRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflowRepository creates a new instance of MockWorkflowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
