// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/nojyerac/aeneas/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockExecutionRepository is an autogenerated mock type for the ExecutionRepository type
type MockExecutionRepository struct {
	mock.Mock
}

type MockExecutionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutionRepository) EXPECT() *MockExecutionRepository_Expecter {
	return &MockExecutionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, execution
func (_m *MockExecutionRepository) Create(ctx context.Context, execution *domain.Execution) error {
	ret := _m.Called(ctx, execution)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Execution) error); ok {
		r0 = rf(ctx, execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExecutionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - execution *domain.Execution
func (_e *MockExecutionRepository_Expecter) Create(ctx interface{}, execution interface{}) *MockExecutionRepository_Create_Call {
	return &MockExecutionRepository_Create_Call{Call: _e.mock.On("Create", ctx, execution)}
}

func (_c *MockExecutionRepository_Create_Call) Run(run func(ctx context.Context, execution *domain.Execution)) *MockExecutionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Execution))
	})
	return _c
}

func (_c *MockExecutionRepository_Create_Call) Return(_a0 error) *MockExecutionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Execution) error) *MockExecutionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockExecutionRepository) Get(ctx context.Context, id string) (*domain.Execution, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Execution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Execution, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Execution); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Execution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExecutionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExecutionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockExecutionRepository_Get_Call {
	return &MockExecutionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockExecutionRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockExecutionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExecutionRepository_Get_Call) Return(_a0 *domain.Execution, _a1 error) *MockExecutionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Execution, error)) *MockExecutionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWorkflow provides a mock function with given fields: ctx, workflowID, opts
func (_m *MockExecutionRepository) ListByWorkflow(ctx context.Context, workflowID string, opts domain.ListOptions) ([]*domain.Execution, error) {
	ret := _m.Called(ctx, workflowID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListByWorkflow")
	}

	var r0 []*domain.Execution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ListOptions) ([]*domain.Execution, error)); ok {
		return rf(ctx, workflowID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ListOptions) []*domain.Execution); ok {
		r0 = rf(ctx, workflowID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Execution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.ListOptions) error); ok {
		r1 = rf(ctx, workflowID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_ListByWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWorkflow'
type MockExecutionRepository_ListByWorkflow_Call struct {
	*mock.Call
}

// ListByWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
//   - opts domain.ListOptions
func (_e *MockExecutionRepository_Expecter) ListByWorkflow(ctx interface{}, workflowID interface{}, opts interface{}) *MockExecutionRepository_ListByWorkflow_Call {
	return &MockExecutionRepository_ListByWorkflow_Call{Call: _e.mock.On("ListByWorkflow", ctx, workflowID, opts)}
}

func (_c *MockExecutionRepository_ListByWorkflow_Call) Run(run func(ctx context.Context, workflowID string, opts domain.ListOptions)) *MockExecutionRepository_ListByWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ListOptions))
	})
	return _c
}

func (_c *MockExecutionRepository_ListByWorkflow_Call) Return(_a0 []*domain.Execution, _a1 error) *MockExecutionRepository_ListByWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_ListByWorkflow_Call) RunAndReturn(run func(context.Context, string, domain.ListOptions) ([]*domain.Execution, error)) *MockExecutionRepository_ListByWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, execution
func (_m *MockExecutionRepository) Update(ctx context.Context, execution *domain.Execution) error {
	ret := _m.Called(ctx, execution)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Execution) error); ok {
		r0 = rf(ctx, execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExecutionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - execution *domain.Execution
func (_e *MockExecutionRepository_Expecter) Update(ctx interface{}, execution interface{}) *MockExecutionRepository_Update_Call {
	return &MockExecutionRepository_Update_Call{Call: _e.mock.On("Update", ctx, execution)}
}

func (_c *MockExecutionRepository_Update_Call) Run(run func(ctx context.Context, execution *domain.Execution)) *MockExecutionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Execution))
	})
	return _c
}

func (_c *MockExecutionRepository_Update_Call) Return(_a0 error) *MockExecutionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Execution) error) *MockExecutionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockExecutionRepository) UpdateStatus(ctx context.Context, id string, status domain.ExecutionStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ExecutionStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockExecutionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status domain.ExecutionStatus
func (_e *MockExecutionRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockExecutionRepository_UpdateStatus_Call {
	return &MockExecutionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockExecutionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status domain.ExecutionStatus)) *MockExecutionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ExecutionStatus))
	})
	return _c
}

func (_c *MockExecutionRepository_UpdateStatus_Call) Return(_a0 error) *MockExecutionRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, domain.ExecutionStatus) error) *MockExecutionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutionRepository creates a new instance of MockExecutionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutionRepository {
	mock := &MockExecutionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
