// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/nojyerac/aeneas/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockStepExecutionRepository is an autogenerated mock type for the StepExecutionRepository type
type MockStepExecutionRepository struct {
	mock.Mock
}

type MockStepExecutionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStepExecutionRepository) EXPECT() *MockStepExecutionRepository_Expecter {
	return &MockStepExecutionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, stepExecution
func (_m *MockStepExecutionRepository) Create(ctx context.Context, stepExecution *domain.StepExecution) error {
	ret := _m.Called(ctx, stepExecution)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StepExecution) error); ok {
		r0 = rf(ctx, stepExecution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStepExecutionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStepExecutionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - stepExecution *domain.StepExecution
func (_e *MockStepExecutionRepository_Expecter) Create(ctx interface{}, stepExecution interface{}) *MockStepExecutionRepository_Create_Call {
	return &MockStepExecutionRepository_Create_Call{Call: _e.mock.On("Create", ctx, stepExecution)}
}

func (_c *MockStepExecutionRepository_Create_Call) Run(run func(ctx context.Context, stepExecution *domain.StepExecution)) *MockStepExecutionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.StepExecution))
	})
	return _c
}

func (_c *MockStepExecutionRepository_Create_Call) Return(_a0 error) *MockStepExecutionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStepExecutionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.StepExecution) error) *MockStepExecutionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByExecution provides a mock function with given fields: ctx, executionID
func (_m *MockStepExecutionRepository) ListByExecution(ctx context.Context, executionID string) ([]*domain.StepExecution, error) {
	ret := _m.Called(ctx, executionID)

	if len(ret) == 0 {
		panic("no return value specified for ListByExecution")
	}

	var r0 []*domain.StepExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.StepExecution, error)); ok {
		return rf(ctx, executionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.StepExecution); ok {
		r0 = rf(ctx, executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StepExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStepExecutionRepository_ListByExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByExecution'
type MockStepExecutionRepository_ListByExecution_Call struct {
	*mock.Call
}

// ListByExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
func (_e *MockStepExecutionRepository_Expecter) ListByExecution(ctx interface{}, executionID interface{}) *MockStepExecutionRepository_ListByExecution_Call {
	return &MockStepExecutionRepository_ListByExecution_Call{Call: _e.mock.On("ListByExecution", ctx, executionID)}
}

func (_c *MockStepExecutionRepository_ListByExecution_Call) Run(run func(ctx context.Context, executionID string)) *MockStepExecutionRepository_ListByExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStepExecutionRepository_ListByExecution_Call) Return(_a0 []*domain.StepExecution, _a1 error) *MockStepExecutionRepository_ListByExecution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStepExecutionRepository_ListByExecution_Call) RunAndReturn(run func(context.Context, string) ([]*domain.StepExecution, error)) *MockStepExecutionRepository_ListByExecution_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, exitCode
func (_m *MockStepExecutionRepository) UpdateStatus(ctx context.Context, id string, status domain.StepExecutionStatus, exitCode *int) error {
	ret := _m.Called(ctx, id, status, exitCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.StepExecutionStatus, *int) error); ok {
		r0 = rf(ctx, id, status, exitCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStepExecutionRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockStepExecutionRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status domain.StepExecutionStatus
//   - exitCode *int
func (_e *MockStepExecutionRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, exitCode interface{}) *MockStepExecutionRepository_UpdateStatus_Call {
	return &MockStepExecutionRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, exitCode)}
}

func (_c *MockStepExecutionRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status domain.StepExecutionStatus, exitCode *int)) *MockStepExecutionRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.StepExecutionStatus), args[3].(*int))
	})
	return _c
}

func (_c *MockStepExecutionRepository_UpdateStatus_Call) Return(_a0 error) *MockStepExecutionRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStepExecutionRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, domain.StepExecutionStatus, *int) error) *MockStepExecutionRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStepExecutionRepository creates a new instance of MockStepExecutionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStepExecutionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStepExecutionRepository {
	mock := &MockStepExecutionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
