// Code generated by mockery v2.53.6. DO NOT EDIT.

package data

import (
	context "context"

	data "github.com/nojyerac/aeneas/data"
	mock "github.com/stretchr/testify/mock"
)

// MockDataSource is an autogenerated mock type for the DataSource type
type MockDataSource struct {
	mock.Mock
}

type MockDataSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataSource) EXPECT() *MockDataSource_Expecter {
	return &MockDataSource_Expecter{mock: &_m.Mock}
}

// GetExample provides a mock function with given fields: ctx, id
func (_m *MockDataSource) GetExample(ctx context.Context, id string) (*data.Example, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExample")
	}

	var r0 *data.Example
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*data.Example, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *data.Example); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Example)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDataSource_GetExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExample'
type MockDataSource_GetExample_Call struct {
	*mock.Call
}

// GetExample is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataSource_Expecter) GetExample(ctx interface{}, id interface{}) *MockDataSource_GetExample_Call {
	return &MockDataSource_GetExample_Call{Call: _e.mock.On("GetExample", ctx, id)}
}

func (_c *MockDataSource_GetExample_Call) Run(run func(ctx context.Context, id string)) *MockDataSource_GetExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDataSource_GetExample_Call) Return(_a0 *data.Example, _a1 error) *MockDataSource_GetExample_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDataSource_GetExample_Call) RunAndReturn(run func(context.Context, string) (*data.Example, error)) *MockDataSource_GetExample_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDataSource creates a new instance of MockDataSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataSource {
	mock := &MockDataSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
