// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_INACTIVE    WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_ACTIVE      WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_ARCHIVED    WorkflowStatus = 3
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_INACTIVE",
		2: "WORKFLOW_STATUS_ACTIVE",
		3: "WORKFLOW_STATUS_ARCHIVED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_INACTIVE":    1,
		"WORKFLOW_STATUS_ACTIVE":      2,
		"WORKFLOW_STATUS_ARCHIVED":    3,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_PENDING     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_SUCCEEDED   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 4
	ExecutionStatus_EXECUTION_STATUS_CANCELED    ExecutionStatus = 5
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_PENDING",
		2: "EXECUTION_STATUS_RUNNING",
		3: "EXECUTION_STATUS_SUCCEEDED",
		4: "EXECUTION_STATUS_FAILED",
		5: "EXECUTION_STATUS_CANCELED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_PENDING":     1,
		"EXECUTION_STATUS_RUNNING":     2,
		"EXECUTION_STATUS_SUCCEEDED":   3,
		"EXECUTION_STATUS_FAILED":      4,
		"EXECUTION_STATUS_CANCELED":    5,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[1].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[1]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

type StepExecutionStatus int32

const (
	StepExecutionStatus_STEP_EXECUTION_STATUS_UNSPECIFIED StepExecutionStatus = 0
	StepExecutionStatus_STEP_EXECUTION_STATUS_PENDING     StepExecutionStatus = 1
	StepExecutionStatus_STEP_EXECUTION_STATUS_RUNNING     StepExecutionStatus = 2
	StepExecutionStatus_STEP_EXECUTION_STATUS_SUCCEEDED   StepExecutionStatus = 3
	StepExecutionStatus_STEP_EXECUTION_STATUS_FAILED      StepExecutionStatus = 4
	StepExecutionStatus_STEP_EXECUTION_STATUS_SKIPPED     StepExecutionStatus = 5
)

// Enum value maps for StepExecutionStatus.
var (
	StepExecutionStatus_name = map[int32]string{
		0: "STEP_EXECUTION_STATUS_UNSPECIFIED",
		1: "STEP_EXECUTION_STATUS_PENDING",
		2: "STEP_EXECUTION_STATUS_RUNNING",
		3: "STEP_EXECUTION_STATUS_SUCCEEDED",
		4: "STEP_EXECUTION_STATUS_FAILED",
		5: "STEP_EXECUTION_STATUS_SKIPPED",
	}
	StepExecutionStatus_value = map[string]int32{
		"STEP_EXECUTION_STATUS_UNSPECIFIED": 0,
		"STEP_EXECUTION_STATUS_PENDING":     1,
		"STEP_EXECUTION_STATUS_RUNNING":     2,
		"STEP_EXECUTION_STATUS_SUCCEEDED":   3,
		"STEP_EXECUTION_STATUS_FAILED":      4,
		"STEP_EXECUTION_STATUS_SKIPPED":     5,
	}
)

func (x StepExecutionStatus) Enum() *StepExecutionStatus {
	p := new(StepExecutionStatus)
	*p = x
	return p
}

func (x StepExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[2].Descriptor()
}

func (StepExecutionStatus) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[2]
}

func (x StepExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepExecutionStatus.Descriptor instead.
func (StepExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

type StepDefinition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command        []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds *int32                 `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepDefinition) Reset() {
	*x = StepDefinition{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepDefinition) ProtoMessage() {}

func (x *StepDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepDefinition.ProtoReflect.Descriptor instead.
func (*StepDefinition) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StepDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepDefinition) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StepDefinition) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StepDefinition) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StepDefinition) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StepDefinition) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Steps         []*StepDefinition      `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=workflow.WorkflowStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowResponse) GetSteps() []*StepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *WorkflowResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StepExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Status        StepExecutionStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=workflow.StepExecutionStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Error         *string                `protobuf:"bytes,7,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecutionResponse) Reset() {
	*x = StepExecutionResponse{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecutionResponse) ProtoMessage() {}

func (x *StepExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecutionResponse.ProtoReflect.Descriptor instead.
func (*StepExecutionResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *StepExecutionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StepExecutionResponse) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepExecutionResponse) GetStatus() StepExecutionStatus {
	if x != nil {
		return x.Status
	}
	return StepExecutionStatus_STEP_EXECUTION_STATUS_UNSPECIFIED
}

func (x *StepExecutionResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepExecutionResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *StepExecutionResponse) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *StepExecutionResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ExecutionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                   `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        ExecutionStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=workflow.ExecutionStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Error         *string                  `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Steps         []*StepExecutionResponse `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutionResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecutionResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecutionResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ExecutionResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ExecutionResponse) GetSteps() []*StepExecutionResponse {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorkflowsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkflowsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowResponse    `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowResponse {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type CreateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Steps         []*StepDefinition      `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateWorkflowRequest) GetSteps() []*StepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CreateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowByIdRequest) Reset() {
	*x = GetWorkflowByIdRequest{}
	mi := &file_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowByIdRequest) ProtoMessage() {}

func (x *GetWorkflowByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowByIdRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowByIdRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowByIdRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type UpdateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Steps         []*StepDefinition      `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowRequest) Reset() {
	*x = UpdateWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowRequest) ProtoMessage() {}

func (x *UpdateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *UpdateWorkflowRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateWorkflowRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateWorkflowRequest) GetSteps() []*StepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ActivateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateWorkflowRequest) Reset() {
	*x = ActivateWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateWorkflowRequest) ProtoMessage() {}

func (x *ActivateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ActivateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ActivateWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ArchiveWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveWorkflowRequest) Reset() {
	*x = ArchiveWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveWorkflowRequest) ProtoMessage() {}

func (x *ArchiveWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ArchiveWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *ArchiveWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ListWorkflowExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowExecutionsRequest) Reset() {
	*x = ListWorkflowExecutionsRequest{}
	mi := &file_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowExecutionsRequest) ProtoMessage() {}

func (x *ListWorkflowExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *ListWorkflowExecutionsRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ListWorkflowExecutionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkflowExecutionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorkflowExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ExecutionResponse   `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowExecutionsResponse) Reset() {
	*x = ListWorkflowExecutionsResponse{}
	mi := &file_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowExecutionsResponse) ProtoMessage() {}

func (x *ListWorkflowExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *ListWorkflowExecutionsResponse) GetExecutions() []*ExecutionResponse {
	if x != nil {
		return x.Executions
	}
	return nil
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *CancelExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionResponse) Reset() {
	*x = CancelExecutionResponse{}
	mi := &file_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionResponse) ProtoMessage() {}

func (x *CancelExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionResponse.ProtoReflect.Descriptor instead.
func (*CancelExecutionResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{17}
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\bworkflow\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x02\n" +
	"\x0eStepDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x123\n" +
	"\x03env\x18\x05 \x03(\v2!.workflow.StepDefinition.EnvEntryR\x03env\x12,\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05H\x00R\x0etimeoutSeconds\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_timeout_seconds\"\xb0\x02\n" +
	"\x10WorkflowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x05steps\x18\x04 \x03(\v2\x18.workflow.StepDefinitionR\x05steps\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.workflow.WorkflowStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc8\x02\n" +
	"\x15StepExecutionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.workflow.StepExecutionStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12 \n" +
	"\texit_code\x18\x06 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\a \x01(\tH\x01R\x05error\x88\x01\x01B\f\n" +
	"\n" +
	"_exit_codeB\b\n" +
	"\x06_error\"\xcb\x02\n" +
	"\x11ExecutionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.workflow.ExecutionStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01\x125\n" +
	"\x05steps\x18\a \x03(\v2\x1f.workflow.StepExecutionResponseR\x05stepsB\b\n" +
	"\x06_error\"D\n" +
	"\x14ListWorkflowsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"Q\n" +
	"\x15ListWorkflowsResponse\x128\n" +
	"\tworkflows\x18\x01 \x03(\v2\x1a.workflow.WorkflowResponseR\tworkflows\"\x92\x01\n" +
	"\x15CreateWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12.\n" +
	"\x05steps\x18\x03 \x03(\v2\x18.workflow.StepDefinitionR\x05stepsB\x0e\n" +
	"\f_description\"9\n" +
	"\x16CreateWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"9\n" +
	"\x16GetWorkflowByIdRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xc1\x01\n" +
	"\x15UpdateWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12.\n" +
	"\x05steps\x18\x04 \x03(\v2\x18.workflow.StepDefinitionR\x05stepsB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\":\n" +
	"\x17ActivateWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"9\n" +
	"\x16ArchiveWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"9\n" +
	"\x16ExecuteWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"n\n" +
	"\x1dListWorkflowExecutionsRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"]\n" +
	"\x1eListWorkflowExecutionsResponse\x12;\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1b.workflow.ExecutionResponseR\n" +
	"executions\"8\n" +
	"\x13GetExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\";\n" +
	"\x16CancelExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\x19\n" +
	"\x17CancelExecutionResponse*\x89\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18WORKFLOW_STATUS_INACTIVE\x10\x01\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18WORKFLOW_STATUS_ARCHIVED\x10\x03*\xcb\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_SUCCEEDED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19EXECUTION_STATUS_CANCELED\x10\x05*\xec\x01\n" +
	"\x13StepExecutionStatus\x12%\n" +
	"!STEP_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSTEP_EXECUTION_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dSTEP_EXECUTION_STATUS_RUNNING\x10\x02\x12#\n" +
	"\x1fSTEP_EXECUTION_STATUS_SUCCEEDED\x10\x03\x12 \n" +
	"\x1cSTEP_EXECUTION_STATUS_FAILED\x10\x04\x12!\n" +
	"\x1dSTEP_EXECUTION_STATUS_SKIPPED\x10\x052\xf8\x03\n" +
	"\x0fWorkflowService\x12P\n" +
	"\rListWorkflows\x12\x1e.workflow.ListWorkflowsRequest\x1a\x1f.workflow.ListWorkflowsResponse\x12S\n" +
	"\x0eCreateWorkflow\x12\x1f.workflow.CreateWorkflowRequest\x1a .workflow.CreateWorkflowResponse\x12K\n" +
	"\vGetWorkflow\x12 .workflow.GetWorkflowByIdRequest\x1a\x1a.workflow.WorkflowResponse\x12M\n" +
	"\x0eUpdateWorkflow\x12\x1f.workflow.UpdateWorkflowRequest\x1a\x1a.workflow.WorkflowResponse\x12Q\n" +
	"\x10ActivateWorkflow\x12!.workflow.ActivateWorkflowRequest\x1a\x1a.workflow.WorkflowResponse\x12O\n" +
	"\x0fArchiveWorkflow\x12 .workflow.ArchiveWorkflowRequest\x1a\x1a.workflow.WorkflowResponse2\xf5\x02\n" +
	"\x10ExecutionService\x12J\n" +
	"\fGetExecution\x12\x1d.workflow.GetExecutionRequest\x1a\x1b.workflow.ExecutionResponse\x12V\n" +
	"\x0fCancelExecution\x12 .workflow.CancelExecutionRequest\x1a!.workflow.CancelExecutionResponse\x12P\n" +
	"\x0fExecuteWorkflow\x12 .workflow.ExecuteWorkflowRequest\x1a\x1b.workflow.ExecutionResponse\x12k\n" +
	"\x16ListWorkflowExecutions\x12'.workflow.ListWorkflowExecutionsRequest\x1a(.workflow.ListWorkflowExecutionsResponseB\rZ\vpb/workflowb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_workflow_proto_goTypes = []any{
	(WorkflowStatus)(0),                    // 0: workflow.WorkflowStatus
	(ExecutionStatus)(0),                   // 1: workflow.ExecutionStatus
	(StepExecutionStatus)(0),               // 2: workflow.StepExecutionStatus
	(*StepDefinition)(nil),                 // 3: workflow.StepDefinition
	(*WorkflowResponse)(nil),               // 4: workflow.WorkflowResponse
	(*StepExecutionResponse)(nil),          // 5: workflow.StepExecutionResponse
	(*ExecutionResponse)(nil),              // 6: workflow.ExecutionResponse
	(*ListWorkflowsRequest)(nil),           // 7: workflow.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),          // 8: workflow.ListWorkflowsResponse
	(*CreateWorkflowRequest)(nil),          // 9: workflow.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil),         // 10: workflow.CreateWorkflowResponse
	(*GetWorkflowByIdRequest)(nil),         // 11: workflow.GetWorkflowByIdRequest
	(*UpdateWorkflowRequest)(nil),          // 12: workflow.UpdateWorkflowRequest
	(*ActivateWorkflowRequest)(nil),        // 13: workflow.ActivateWorkflowRequest
	(*ArchiveWorkflowRequest)(nil),         // 14: workflow.ArchiveWorkflowRequest
	(*ExecuteWorkflowRequest)(nil),         // 15: workflow.ExecuteWorkflowRequest
	(*ListWorkflowExecutionsRequest)(nil),  // 16: workflow.ListWorkflowExecutionsRequest
	(*ListWorkflowExecutionsResponse)(nil), // 17: workflow.ListWorkflowExecutionsResponse
	(*GetExecutionRequest)(nil),            // 18: workflow.GetExecutionRequest
	(*CancelExecutionRequest)(nil),         // 19: workflow.CancelExecutionRequest
	(*CancelExecutionResponse)(nil),        // 20: workflow.CancelExecutionResponse
	nil,                                    // 21: workflow.StepDefinition.EnvEntry
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
}
var file_workflow_proto_depIdxs = []int32{
	21, // 0: workflow.StepDefinition.env:type_name -> workflow.StepDefinition.EnvEntry
	3,  // 1: workflow.WorkflowResponse.steps:type_name -> workflow.StepDefinition
	0,  // 2: workflow.WorkflowResponse.status:type_name -> workflow.WorkflowStatus
	22, // 3: workflow.WorkflowResponse.created_at:type_name -> google.protobuf.Timestamp
	22, // 4: workflow.WorkflowResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: workflow.StepExecutionResponse.status:type_name -> workflow.StepExecutionStatus
	22, // 6: workflow.StepExecutionResponse.started_at:type_name -> google.protobuf.Timestamp
	22, // 7: workflow.StepExecutionResponse.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 8: workflow.ExecutionResponse.status:type_name -> workflow.ExecutionStatus
	22, // 9: workflow.ExecutionResponse.started_at:type_name -> google.protobuf.Timestamp
	22, // 10: workflow.ExecutionResponse.finished_at:type_name -> google.protobuf.Timestamp
	5,  // 11: workflow.ExecutionResponse.steps:type_name -> workflow.StepExecutionResponse
	4,  // 12: workflow.ListWorkflowsResponse.workflows:type_name -> workflow.WorkflowResponse
	3,  // 13: workflow.CreateWorkflowRequest.steps:type_name -> workflow.StepDefinition
	3,  // 14: workflow.UpdateWorkflowRequest.steps:type_name -> workflow.StepDefinition
	6,  // 15: workflow.ListWorkflowExecutionsResponse.executions:type_name -> workflow.ExecutionResponse
	7,  // 16: workflow.WorkflowService.ListWorkflows:input_type -> workflow.ListWorkflowsRequest
	9,  // 17: workflow.WorkflowService.CreateWorkflow:input_type -> workflow.CreateWorkflowRequest
	11, // 18: workflow.WorkflowService.GetWorkflow:input_type -> workflow.GetWorkflowByIdRequest
	12, // 19: workflow.WorkflowService.UpdateWorkflow:input_type -> workflow.UpdateWorkflowRequest
	13, // 20: workflow.WorkflowService.ActivateWorkflow:input_type -> workflow.ActivateWorkflowRequest
	14, // 21: workflow.WorkflowService.ArchiveWorkflow:input_type -> workflow.ArchiveWorkflowRequest
	18, // 22: workflow.ExecutionService.GetExecution:input_type -> workflow.GetExecutionRequest
	19, // 23: workflow.ExecutionService.CancelExecution:input_type -> workflow.CancelExecutionRequest
	15, // 24: workflow.ExecutionService.ExecuteWorkflow:input_type -> workflow.ExecuteWorkflowRequest
	16, // 25: workflow.ExecutionService.ListWorkflowExecutions:input_type -> workflow.ListWorkflowExecutionsRequest
	8,  // 26: workflow.WorkflowService.ListWorkflows:output_type -> workflow.ListWorkflowsResponse
	10, // 27: workflow.WorkflowService.CreateWorkflow:output_type -> workflow.CreateWorkflowResponse
	4,  // 28: workflow.WorkflowService.GetWorkflow:output_type -> workflow.WorkflowResponse
	4,  // 29: workflow.WorkflowService.UpdateWorkflow:output_type -> workflow.WorkflowResponse
	4,  // 30: workflow.WorkflowService.ActivateWorkflow:output_type -> workflow.WorkflowResponse
	4,  // 31: workflow.WorkflowService.ArchiveWorkflow:output_type -> workflow.WorkflowResponse
	6,  // 32: workflow.ExecutionService.GetExecution:output_type -> workflow.ExecutionResponse
	20, // 33: workflow.ExecutionService.CancelExecution:output_type -> workflow.CancelExecutionResponse
	6,  // 34: workflow.ExecutionService.ExecuteWorkflow:output_type -> workflow.ExecutionResponse
	17, // 35: workflow.ExecutionService.ListWorkflowExecutions:output_type -> workflow.ListWorkflowExecutionsResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_workflow_proto_msgTypes[0].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[2].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[3].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[6].OneofWrappers = []any{}
	file_workflow_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
